name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List root directory contents
      run: ls -la

    - name: List project folder contents
      run: ls -la Holo-Test-Automation-Task

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        cd Holo-Test-Automation-Task
        npm install

    - name: Run Cypress Tests
      run: |
        cd Holo-Test-Automation-Task
        npx cypress run
